### PR TITLE
Added prop to remove links in date numbers in month view

### PR DESCRIPTION
**Pull request by manutenfruits**
Fixes this: https://github.com/intljusticemission/react-big-calendar/issues/125

Not sure how the best prop/argument schema should be, so I'm happy to take suggestions.

### CODE REVIEW

**Comment by tobiasandersen** [comment]
Couldn't this be solved using e.g. `getDrilldownView`?

**Comment by jquense** [comment]
i think the preventing of links could, but not if you don't want the links at all...i'm pretty on the fence about this (hence why it's languished so long). The api isn't great here, but maybe its a necessary use case?

**Comment by tobiasandersen** [comment]
Yeah you're right, I just feel like there's a risk we end up with way too many props for small things like this. I much prefer the render prop approach (or component prop like we already make use of).

**Comment by jquense** [comment]
yeah i agree, if we were to handle this it should be via a component or renderFoo prop

**Comment by tobiasandersen** [comment]
I'll go ahead and close this since it's been a while. Thanks for doing this though @manutenfruits! And if you want to update the PR to use a component or render prop instead of a boolean, just re-open! :)

**Comment by v-nlondhe** [comment]
I am also facing same issue using react big calendar after rendering calendar each day number rendering as anchor tag i need to convert to button tag please let me know is there is props or any custom way to add button on each date on calendar.

**Pull request closed without merging**
