### PR TITLE
Add support for onSelectEvent and onDoubleClickEvent in Agenda view

### PR DESCRIPTION
**Pull request by silentsakky**
Add support for onSelectEvent and onDoubleClickEvent in Agenda view

### CODE REVIEW

**Comment by jku6** [comment]
up

**Comment by morgs32** [comment]
@jquense have any thoughts on this?

**Comment by jquense** [comment]
thanks for the work @silentsakky my concern here is that this only really makes sense with the default simple rendering. In most apps i've used RBC in i've use more complicated custom agenda components that contain their own buttons and clickable chrome. That would be really hard to handle with this addition because the event bubbling would fire for clicks inside the component.

This is already potentially a problem for the day view event clicks but i've not personally had that issue. In any case I think there should be a way to opt out of hte default behavior per view, so I may want the clicks for month or day views but not agenda. It's probably enough to pass the current view into the handler so a user can switch off of it

**Comment by m1nd** [comment]
Up

**Comment by jquense** [comment]
Hey y'all I'm closing this for now per my comments above, if someone wants to take a stay at a more robust addition I'd be happy to take it but folks are unhelpfully pinging ppl on this issue at this point so let's close it out

**Pull request closed without merging**
