### PR TITLE
feat(event): specific background color for each event

### PR DESCRIPTION
**Pull request by mohammadmoozeh**
Just add 'bgColor' field in object.

### CODE REVIEW

**Comment by jquense** [comment]
You can use eventPropGetter for this already happily 👍

**Comment by mohammadmoozeh** [comment]
Would you give me an example?

**Comment by mohammadmoozeh** [comment]
@jquense I tried eventPropGetter but it changes all events color.
Could you help me?
Thanks

**Comment by jquense** [comment]
It's a function that's called for _each_ event change what you return for only the events you want.

```
event => ({ className: event.isBusy ? 'red' : null })
```

**Comment by PaitoAnderson** [comment]
Just in case anyone needs a more complete example implementation...

```jsx
<Calendar
    events={this.state.events}
    eventPropGetter={(event, start, end, isSelected) => {
        if (event.color) {
            return { style: { backgroundColor: event.color }}
        }
        return {}
    }}
/>
```

**Pull request closed without merging**
