### PR TITLE
Add boolean allDaySlot prop to Calendar to match FullCalendar

### PR DESCRIPTION
**Pull request by kat3kasper**
Determines if the "all-day" slot is displayed at the top of the calendar.
When hidden with false, all-day events will not be displayed in agenda views.

Boolean, default: true

### CODE REVIEW

**Comment by jquense** [comment]
Hi there! thanks for the PR. There are quite a few issues about this particular feature already. We don't allowing hiding the AllDay slots because it hide events that are all-day or span a day boundary. Overall I try to avoid adding options that can lead to broken configuration for consumers.

**Comment by kat3kasper** [comment]
@jquense thanks for the quick response. Anyway we can add a warning or something. Its great to have the react version available but this functionality is available in FullCalendar. Would prefer not to have to publish a new npm package that I will have to update everytime things change here. Any ideas how to work around that?

**Comment by arecvlohe** [comment]
I imagine forking this repo and adding any additional functionality is an option

**Comment by jquense** [comment]
I don't think forking is necessary. There is an issue or two in the tracker that details a css style for doing it. I can be open to the toggle in the api but the docs need to be clear the cost and potential downsides

**Comment by Auchindoun** [comment]
We might be able to pair this with my PR, so that they can disable the all day column, and any days that DO span all day will take up the whole day slot. I could make the adjustment. And of course have big warning that this can cause annoyances for busy schedules. Thoughts @jquense @kat3kasper?

**Comment by jquense** [comment]
Works for me

**Comment by Auchindoun** [comment]
@kat3kasper do you want me to give you access to my fork, or do you want me to add your changes in to my PR?

**Comment by francomendoza** [comment]
@Auchindoun @kat3kasper is there an update on this?

**Comment by tobiasandersen** [comment]
This is quite old now, so I'll close it for now. If anyone wants to add the changes requested by @jquense, feel free to re-open again. Thanks everyone and especially @kat3kasper for opening the PR! 

For anyone looking for a solution, please read through https://github.com/intljusticemission/react-big-calendar/issues/203.

**Comment by marwej** [comment]
This would be very useful for me too. If I can assure, in my application, that no event will ever span several days, then I don't want to show the "All day" row. With the new resource row (great feature!), suggested CSS won't work since the "All day" row can be both second row (without resources) and third row (with resources). (I try to avoid CSS and use inline styles as much as possible too.)

**Comment by rizvified** [comment]
I think this is super useful. As my project implementation does not require an all day view and using CSS or inline styles to hide it is not a good solution.

**Comment by SrishtiSingh1902** [comment]
when I am writing allday:false it is giving error is the start and end accessor expecting particular datetime format , Can anybody suggest ?

**Pull request closed without merging**
