### PR TITLE
Add custom timeSlotWrapper support

### PR DESCRIPTION
**Pull request by spacetag**
Expose timeSlotWrapper so a custom timeSlotWrapper can be passed through! 😃

### CODE REVIEW

**Comment by arecvlohe** [comment]
@spacetag Can you also update the docs to reflect this is another custom component?

**Comment by spacetag** [comment]
Hi @arecvlohe! Yes, I can update the docs!

Actually, I think the docs are autogenerated, so I think it may already be done!

If this isn't what you had in mind, let me know!

Screenshot of BigReactCalendar API docs

**Comment by arecvlohe** [comment]
Yes, that is what I was talking about. Even better if it's auto-generated for you.

**Comment by spacetag** [comment]
Great! 😇
P.S. What is the usual time between PR and next npm version? We would like to use this in our app soon! 😊

**Comment by arecvlohe** [comment]
@spacetag It's usually every month or so a release is shipped. I would bet it will be a couple weeks before it does get released.

**Comment by abenoit** [comment]
Hi there ! 

Thanks for the great job, react-big-calendar works great and makes my app awesome :) 

Any news on this timeSlotWrapper feature release ? 
I am going to need it to add some identifiers and stuff 😀

**Comment by romaindso** [comment]
Hi, 
I'm interested too 
Our Q&A team needs Ids to identify components in their end to end tests

**Pull request merged**
