### PR TITLE
Highlight today's columns

### PR DESCRIPTION
**Pull request by mawek**
Just updated version of https://github.com/intljusticemission/react-big-calendar/pull/132 according to your comment

### CODE REVIEW

**Comment by ffdead** [comment]
+1

**Comment by ffdead** [comment]
Hi guys,

It would be great to have this `rbc-today` class, please also add it to the `rbc-header` - we need to be able to style this too.

Big thanks!

**Comment by jquense** [comment]
hey @mawek can you add back the `/lib` git ignore?

and as @ffdead said add it to the header cell as well?

**Comment by mawek** [comment]
updated

**Comment by ffdead** [comment]
Hi guys, great stuff. big thanks for working on this!

I have a project ending beginning of next week and really need this feature. @jquense do you think there's any chance we could get this merged this week and a new version published?

**Comment by og2t** [comment]
Hi ILM! I am working on a functionality that uses the today's highlight feature too – it would be awesome if you could merge that PR and push the NPM :) Many thanks! 👍

**Comment by jquense** [comment]
thanks ya'll

should be released soon

**Comment by ffdead** [comment]
@jquense Big thanks for all the work on this great component!  

Any idea of when the next release will be published?

**Pull request merged**
