### PR TITLE
Add an optional property for initially selected event

### PR DESCRIPTION
**Pull request by mkretz**
I am using big calendar on a view which the user jumps to by clicking on an url in an email. When the calendar is displayed I want the event referenced in the url to be selected. 

My proposed solution: add an optional property `initialSelection` to `Calendar`. The property contains one element of `events`. If the property is set, `handleSelectEvent` is called after the component has mounted with this element as argument.

### CODE REVIEW

**Comment by jquense** [comment]
Hi there, thanks for the PR! I think the feature you want is already there fortunately. The prop is defaultSelected (like value and defaultValue on react inputs)

**Comment by mkretz** [comment]
You're right, it works! Thanks for the hint! Will close this PR. Just out of interest: I cannot find this behaviour when going through the code. How is this implemented?

**Comment by jquense** [comment]
It's handled via the uncontrollable library used in Calendar

**Comment by mkretz** [comment]
Ok, I will have closer look at uncontrollable. Closing the PR now. Thanks!

**Pull request closed without merging**
