### PR TITLE
Add Resource view

### LINKED ISSUE #13: Resource view, feature request
The component is awesome - the only thing missing for me is a resource view. 

It is often the case to add resources to a calendar event: Eg. a car vendor could add a sales agent and a car model to the event. Now it is easy enough to render the event contents with custom color and text, but events will still be mixed up in the Week/Day columns.

I would like a Week like view, but instead of the week days it would show resource names, displaying the resources' events in the respective columns.

The api/props can be very simple. I have the following props in mind:
- resourceAccessor, 
  **resourceAccessor**`= 'salesguy_id'`
- the list of resources, 
  **resources**`= {  [{id: 1, name: 'John'}, {id:2, name: 'Linda'}]  }`
- a function to test membership, 
  **resourceMembership** `= { (resource, event) => resource.id == event.salesguy_id  }`
- a renderable node as resource column headers, 
  **resourceHeader**`= { (resource) => resource.name }`
- an option to show the resource view in the toolbar, 
  **views**`= ['month', 'week', 'day', 'agenda', 'resource']`
  **messages**`= { ...messages, resource: 'Sales agent view' }`

Like this we could also easily switch between different resource categories - eg sales agents and available car models, calling that "Events by sales agent view, Events by available cars".
Any resource restriction rules are handled by the application, but the display can easily be handled by the calendar.

Interested to know what you think about it,
raf

### PR DESCRIPTION
**Pull request by sabarasaba**
Heya,

I'm back from holidays, but have a lot of stuff on my plate at the moment and I don't know how much more time I'll be able to put on this pr. I'm hopeful someone else that is in need of it will be able to pick it up and make the few small things that are needed:

- [ ] The `Resource` and `ResourceGrid` are just duped files from `Day` and `TimeGrid` files with some extra added functionality. I'd be much happier if we could somehow DRY it up.
- [ ] Ideally when having lots of resources you should be able to have a minimum amount of resources that are shown and the rest would be hidden and shown upon scrolling horizontally (pretty much like an excel grid would work). Also the resource headers should always be visible, only cells would scroll.
- [ ] It needs an proper demo in the `/examples/demos` folder and documentation.

I've added a `story` that shows how the resource view works and example data in `stories/resourceEvents.js`.

Fixes #13 and others.

### CODE REVIEW

**Comment by jquense** [comment]
thanks for this! looks good. if you want to open up your branch to allow pushes then I may be able to jump in and contribute a bit

**Comment by sabarasaba** [comment]
@jquense awesome, just added you as a collaborator :)

**Comment by TeaBough** [comment]
I'm SO looking forward this feature ! Has anybody planned to work on this any time soon ?

**Comment by TeaBough** [comment]
It would be great to have a resource view for the week view as well ...

**Comment by TeaBough** [comment]
I've created https://github.com/intljusticemission/react-big-calendar/pull/423, that serve the same purpose as this PR. The difference is that the logic of the resource is done directly in the TimeGrid instead of creating a `ResourceGrid` which DRY things up and allow to enjoy resource in the week view as well.

**Comment by mukesh-n-crest** [comment]
Any update regarding the PR for vertical resource view? please do it as soon as possible because i need it urgently.

Thanks in advance.

**Comment by sabarasaba** [comment]
@mukesh-n-crest that aint how it works papi

**Comment by TeaBough** [comment]
@jquense @sabarasaba  I think we can close this PR since https://github.com/intljusticemission/react-big-calendar/pull/423 has been merged

-

**Comment by asharafshahi** [comment]
Hi guys, just to confirm, is this feature available now?  The day-view calendar with all the rooms across the top is beautiful.  Any documentation on how to set it up?  Thanks!

**Comment by sabarasaba** [comment]
@asharafshahi This implementation I did never ended up being merged but there was another PR that actually added it in a different way. Not sure about its API thought, but might be worth asking there :)

**Pull request closed without merging**
