### PR TITLE
Date-fns localizer

### PR DESCRIPTION
**Pull request by harel**
An update on a previous PR which was closed, updated to the latest date-fns 2.0 specs.

### CODE REVIEW

**Comment by jquense** [comment]
thanks!

**Comment by TheMoonDawg** [comment]
I've recently started using date-fns, and I love it. Awesome to see this supported!

**Comment by antoinerousseau** [comment]
hey, thanks for this! could we get it on npm please? :)

**Comment by antoinerousseau** [comment]
Isn't `date-fns/parse` unused in the localizer?

**Pull request merged**
