### PR TITLE
properties types fixed

### PR DESCRIPTION
**Pull request by Sigura**
if messages is 
```javascript
<BigCalendar
  events={events}
  messages={{
    previous: <i className="fa fa-chevron-left" />,
    next: <i className="fa fa-chevron-right" />
  }}
/>
```
then warning:
`Warning: Failed propType: Invalid prop 'messages.previous' of type 'object' supplied to 'Calendar', expected 'string'. Check the render method of 'Uncontrolled(Calendar)'.`

There is fix

### CODE REVIEW

**Comment by antoinerousseau** [comment]
why did you commit the `lib/` folder?!

**Comment by antoinerousseau** [comment]
Also, you can use `PropTypes.node` which includes `string` and `element`

https://facebook.github.io/react/docs/reusable-components.html

> `React.PropTypes.node`:
> Anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types.

**Comment by jquense** [comment]
gonna close since it includes a bunch of noise from the lib folder. will take a PR that just adjsuts the propType to `node` though if anyone wants

**Comment by antoinerousseau** [comment]
You already did in #40 ;-)

**Comment by jquense** [comment]
lol

**Pull request closed without merging**
