### PR TITLE
Resizable Events

### PR DESCRIPTION
**Pull request by jnmandal**
This PR adds the ability to resize events to the DND plugin, as discussed in issue https://github.com/intljusticemission/react-big-calendar/issues/382. It includes:

bug fix to core:
* `eventComponent` was being destructured incorrectly in the `DayColumn` component's `renderEvents` function (so it was always undefined)

enhancements to dragAndDrop addon:
* passing prop `resizable` will have the wrapper use a new component `ResizableEvent` as the `eventComponent` for the calendar
* the `onEventResize` callback will give the ability to hook into the DND wrapping. It receives:
  * `resizeType`: 'drag' or 'drop' based on what type of interaction is causing the resize
  * `eventData`: object containing the original event as well as a new `end` for the event

gotchas:

Since only the original event object is accessible through react-dnd... In the `onEventResize` callback you will not be able to use Array.prototype.indexOf for finding the event again -- unless you continue to mutate the original event and splice it into the cloned events array... but I'm not sure if we would want to recommend that practice

### CODE REVIEW

**Comment by jquense** [comment]
hey there thanks a lot for the PR! Sorry i'm a bit slow to review I'm a bit sort on time at the moment but it's really appreciated.

I do think I would at least split this into a separate addon, so folks can use resizing without drag and drop if they want.

**Comment by jnmandal** [comment]
Hey @jquense no worries. Thanks for building out this calendar component.

I did think about the concept of DnD and Resizable being separate but the way I implemented it, one would be useless without the other.  My goal here was to offer the functionality found in google calendar; there, you can only resize from the bottom so to adjust an event's duration and start time you need both resizeable and drag and drop functions. 

We could definitely break it out and offer a Calendar.app style experience where events are resizable at top and bottom but I'm worried it will be a bit of duplicated code/functionality between the DnD addon and the Resizable addon.

**Comment by jquense** [comment]
@jnmandal sorry for the delay 😳 Why would they be useless seperated? It seems like you make use of react-dnd but that's ok, if a user uses both addons the dependencies will be shared.

I don't mind them being together honestly but I'd like to be able to disable drag and drop and only use resize if I wanted.

**Comment by jnmandal** [comment]
Hey @jquense no worries. I just mean the functionality this PR provides is just to allow the end date of an event to be changed. I did not add a resizable anchor to the top.

On Calendar.app you can resize both top and bottom (start and end) but in google calendar, only bottom (end). I only implemented the "google calendar" resizing so its not very useful decoupled from the ability to drag and drop the whole event as well.

**Comment by jquense** [comment]
ah I gotcha, that makes sense. still folks may just want to change the duration if not the start time of the event. Would it be a lot of trouble to make them individually togglable? We can totally keep them in the same addon so you should still get the benefit of them being coupled right?

**Comment by Raman16** [comment]
Thank you so much for adding Resizable Event feature to BigCalendar.

**Comment by jnmandal** [comment]
Sorry for delay on fixing this up, I have been slammed; I will look into decoupling dragging from the resizing this weekend

**Comment by arecvlohe** [comment]
What is the estimated timetable for this feature? Just wondering

**Comment by jquense** [comment]
whenever folks get it done :)

**Comment by jnmandal** [comment]
Was hoping to resolve issues last weekend but I'm a little behind on some projects right now 😅  I think I can take a stab at this sometime this week

**Comment by arecvlohe** [comment]
I will take a look at your fork @jnmandal, let me know if I can help in anyway.

**Comment by arecvlohe** [comment]
@jnmandal I think if it's okay, we will run with the fork that you have so this feature can be integrated in in our project. Thanks for working on this. We will try to contribute if we are able to take it further.

**Comment by jnmandal** [comment]
Yeah @arecvlohe I am unfortunately still in process of converting this into a separate addon -- took a stab yesterday while on an airplane. I'm grappling w/ how to do it w/o duplicating so much of the dnd addon and then also making them play nice together. TBH, I am also planning on running with fork for now as I'm still slammed and need to ship.

If someone else has idea for implementation or wants to take over please go for it.

**Comment by gazab** [comment]
I think it's foolish to try to seperate them completely. Isn't it better to just make it possible to turn them off separately while still being part of the dnd addon? @jquense said that was fine.

**Comment by jquense** [comment]
Yes! sorry if was unclear i'm ok with this being in the same addon as DND

**Comment by AlexMarvelo** [comment]
I'm ready to help with this. @jnmandal will look into your fork

**Comment by AlexMarvelo** [comment]
I'm ready to help with this. @jnmandal, I will look into your fork

**Comment by arecvlohe** [comment]
So it looks like having this in the dnd addon is fine. So that's clear. What @jquense is asking for is that both ends be toggle-able in day view. 

I will be working on adding this toggle-ability to the month view where users can adjust the dates by toggling the left and right parts of the event. If I can get this working relatively soon then I will tackle the adjustment to make both end toggle-able in the day view.

Example:
event-lengthen

**Comment by arecvlohe** [comment]
I have a working prototype for resizing month events. @jnmandal These changes were made off of your fork, so I could push to your repo to get these changes into your fork/branch. I will also work on adding toggling to the top and of the event in week/day view. Please add any comments you might have @jquense. Also I am wondering if I should just push my branch so you can see what the code looks like. Just let me know.

resize-month-event

**Comment by arecvlohe** [comment]
I have completed a prototype for the month and week/day resize events that can be resized by dragging the left/right and top/bottom of the elements respectively. Here is what they look like thus far:

## Week
resize-event-week

## Month
resize-month-event

I am hesitant to start another PR but if I don't connect with @jnmandal then I think I might have to. What are your thoughts @jquense?

**Comment by arecvlohe** [comment]
If you want to check out the relevant changes go [here](https://github.com/intljusticemission/react-big-calendar/compare/master...arecvlohe:feature/resize-events-month-view)

**Comment by jnmandal** [comment]
@arecvlohe thanks for doing this. Looks like a big improvement. I added you as collaborator to my fork so you can push there and update this PR and/or feel free to open additional. Sorry I have been MIA.

**Comment by arecvlohe** [comment]
@jnmandal Thanks! I pushed to your branch for now. I am going to look into #577 and see how I can improve the hover functionality.

**Comment by jnmandal** [comment]
@jquense check out https://github.com/intljusticemission/react-big-calendar/pull/578 its the same as this PR but cleaner w/ a rebase @arecvlohe kindly picked up my slack and made the improvements requested. thanks all

**Pull request closed without merging**
