### PR TITLE
Add `.rbc-current` class to the "selected" date

### PR DESCRIPTION
**Pull request by MattWilliamsDev**
Add `.rbc-selected` according to `this.props.date`.

### CODE REVIEW

**Comment by MattWilliamsDev** [comment]
FWIW, I have been using this for a month in development env. for our app without issue.

Just wanted to check the status of this one.

**Comment by MattWilliamsDev** [comment]
This fixes issue #20

**Comment by jquense** [comment]
sorry! would you mind just changing the class name to `rbc-current`, to avoid naming ambiguity between the current calendar date and selected cells

**Comment by MattWilliamsDev** [comment]
Done!  Thanks again for the response.  I left for vacation the evening I made the comments and just got back to make the change.

**NOTE:** This doesn't add any styles, as I wasn't sure how/if you would want to utilize it by default.  If you want more details on how we are using it, I would be happy to fill you in.

**Comment by MattWilliamsDev** [comment]
*Bump*

**Comment by jquense** [comment]
thanks!

**Pull request merged**
