### PR TITLE
No longer duplicating events while dragging/resizing

### PR DESCRIPTION
**Pull request by SudoPlz**
Here's a set of fixes to the dnd add-on.
The most important change is this:

Expected behaviour:

Actual behaviour:

This PR fixes that by creating a subset of events (that doesn't contain the updatee - the event that is being dragged).

That happens for both move and resize actions.

### CODE REVIEW

**Comment by jquense** [comment]
where is the relevant change here? A quick glance at this, i think i prefer the current strategy which is to just hide the dragging event visually with css, instead of trying to not render it

**Comment by SudoPlz** [comment]
hmm, but the events are not hiding at all. Am I missing something? Which css class is responsible for hiding the duplicate event?

**Comment by SudoPlz** [comment]
Do you want me to change the PR and make it so that the event get's hidden with CSS and not removed from the dom?

**Comment by jquense** [comment]
Hmm it should already be doing it!

**Comment by SudoPlz** [comment]
Interesting, that's not the case on my end, I'll check it out.

**Comment by SudoPlz** [comment]
https://github.com/intljusticemission/react-big-calendar/pull/959

**Pull request closed without merging**
