### PR TITLE
add customizeClass for rbc-row-segment

### PR DESCRIPTION
**Pull request by pl2476**
image
image

### CODE REVIEW

**Comment by jquense** [comment]
Hi there, I think you can already accomplish what you want here with `eventPropGetter` which lets you return a custom class based on the event

**Comment by pl2476** [comment]
ok, I get it, thank you,

**Comment by pl2476** [comment]
Can I add style to onDropFromOutside ? So I can get the custom style when dragging external data.

**Comment by pl2476** [comment]
> Can I add style to onDropFromOutside ? So I can get the custom style when dragging external data.

@jquense

**Pull request closed without merging**
