### PR TITLE
The time indicator interval is now handled by TimeGrid

### PR DESCRIPTION
**Pull request by SudoPlz**
- Fixes: https://github.com/intljusticemission/react-big-calendar/issues/1017

Unfortunately this pr also contains the changes from https://github.com/intljusticemission/react-big-calendar/pull/1018 but I take it that 1018 will be merged anyway.

### CODE REVIEW

**Comment by jquense** [comment]
I think i'm pretty comfortable not fixing #1018, it's a real edge case, and `now` is used a lot of places besides this one which would still be sort of broken even with this change.

**Comment by SudoPlz** [comment]
Is there any reason why you don't want to at least fix this one? I don't see any possible downsides.

**Comment by jquense** [comment]
The downsides are minor, but big enough that i moved from having the indicator in the TimeGrid to the DayColumn. We want to avoiding keeping an interval state value in the grid to reduce unnecessary cascading updates in components that don't need it. In this case the whole grid updates to move the line in one column. IT doesn't seem like a big thing, but especially with Resources full rerenders can be costly. It's a minor thing but that's weighed with i think a minor bug

**Comment by SudoPlz** [comment]
Got it, closing for now then.

**Comment by SudoPlz** [comment]
@jquense I'm re-opening this because I'd like to fix the issue.

This time, I created a standalone component called `TimeIndicatorLine` that only updates itself every minute.
That way we avoid unnecessary cascading updates, and update the indicator line.

Also, because the current active day background of the current day remains the same even even if a day changes, I added a timer inside TimeGrid that ONLY updates the TimeGrid if the day changes (that means 1 re-render per 24 hours which I think is fine).

Can you review that please?
It should be pretty straight forward and without side-effects when it comes to performance.

**Pull request closed without merging**
