### PR TITLE
No longer hiding the header when we only show one day

### PR DESCRIPTION
**Pull request by SudoPlz**
I don't see any reason why that should be hidden with javascript.
That causes an issue in our project, and I think we should let people decide wether they want to hide that or not (with CSS preferably)

### CODE REVIEW

**Comment by jquense** [comment]
I don't think this is a great default. You essentially have two headers now for the Day view the toolbar label and now the single header. It makes sense from implementation perspective but a lot less so from a visual usage one.

**Comment by SudoPlz** [comment]
Maybe we should hide it with css then otherwise this behavior can not be overwritten

**Comment by jquense** [comment]
Can you talk through your use case a bit so I have a sense why that would be desirable? It can be tough to discussion additions with a clear sense of what we're gain :)

**Comment by SudoPlz** [comment]
@jquense Here's how we want our implementation to look like:

https://cl.ly/878d880870cc/%255B3c637355dcb42019c86bcfb82b68550a%255D_shouldBe.gif

Here's how it looks like now:

https://cl.ly/b414c5ea7cdc/Screen%20Recording%202018-10-02%20at%2001.46%20PM.gif


I made some changes so that it now hides itself with CSS instead of javascript.
This should make it so that the behaviour remains the same, but it allows that the visibility to be changed via css.

**Comment by jquense** [comment]
thanks!

**Pull request merged**
