### PR TITLE
feat: Slot group prop getter (#1471)

### PR DESCRIPTION
**Pull request by emilienh**
Added a slotGroupPropGetter property to allow for custom styles to be passed to time slot groups. Useful for dynamic calendar sizing.

### CODE REVIEW

**Comment by ntelkedzhiev** [comment]
I need this too.

**Comment by guillaumekh** [comment]
This PR is marked as blocked because of a GH billing issue. 
Can we merge it ?

**Comment by ntelkedzhiev** [comment]
Please merge.

**Comment by guillaumekh** [comment]
thanks @jquense !

**Pull request merged**
