### PR TITLE
fix: change tooltipAccessor key to 'tooltip' from 'title'

### PR DESCRIPTION
**Pull request by SergeyBelofost**
Events tooltip was from title of them. Changed key of tooltipAccessor to 'tooltip' for correct work.

### CODE REVIEW

**Comment by jquense** [comment]
thanks for the PR. This is actually intentional. The default is to use the title of the event for the tooltip. If you want use `tooltip` in your app, then you can specify `tooltipAccessor='tooltip'` on your calendar

**Comment by SergeyBelofost** [comment]
i have "Property 'tooltipAccessor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<BigCalendar..."

**Comment by SergeyBelofost** [comment]
> thanks for the PR. This is actually intentional. The default is to use the title of the event for the tooltip. If you want use `tooltip` in your app, then you can specify `tooltipAccessor='tooltip'` on your calendar

**Property 'tooltipAccessor' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<BigCalendar**

**Comment by jquense** [comment]
That is a problem with the typescript types, which we don't maintain. I'd send DT a PR if it's missing there.

**Comment by Angelk90** [comment]
Hi @jquense , it would be possible to implement the possibility of being able to replace the corrwnte tooltip of the event with one that is passed as props to the calendar.

For example I would like to use this: https://material-ui.com/components/tooltips/

**Pull request closed without merging**
